- name: List objects from all the buckets
  hosts: localhost
  collections:
    - oracle.oci
  vars:

    sample_bucket_name: "sample_bucket"
    sample_object_name: "sample_object"


    compartment_id: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"

  tasks:
    - name: Get all the buckets in the namespace

      oci_object_storage_namespace_facts:
      register: namespace_name

    - name: list bucket facts
      oci_object_storage_bucket_facts:
        namespace_name: "{{ namespace_name.namespace }}"
        compartment_id: "{{ compartment_id }}"
      register: ocibuckets

    - name: Get all objects from all the buckets
      oci_object_storage_object_facts:
        namespace_name: "{{ namespace_name.namespace }}"
        bucket_name: "{{ item.name }}"
      with_items: "{{ ocibuckets.buckets }}"
      register: output
    - name: Print objects list
      debug:
        msg: 'Bucket: {{item.item.name}}, Objects: {{item.objects}}'
      loop: "{{output.results}}"
      loop_control:
        label: "{{item.item.name}}"

